### ISSUE TITLE
404 Page at bottom of vcf file

### ISSUE THREAD

**Issue by spAnser** [nfourtythree/craft-vcard#2]
Craft still attempts to render the linked page and it appears at the bottom of the VCF file.

Creating an empty file at `/templates/actions/vCard.twig` will fix this problem.

Maybe this can be fixed within the plugin though.

**Comment by nfourtythree** [comment]
Hi,

I have updated this to stop the generation of 404s from within the controller so no need to create an empty file.

It is fixed in the [latest relase ](https://github.com/nfourtythree/craft-vcard/releases/tag/1.0.1)

Hope this helps
