### ISSUE TITLE
phoneNumber type Fax

### ISSUE THREAD

**Issue by waswebb** [nfourtythree/craft-vcard#6]
Hi

I'm using your Plugin, it wroks still great. But here is no way to add a faxNumber. Can you add this option to your Plugin?

Thank you

**Comment by nfourtythree** [comment]
Hi @waswebb 

I believe you should be able to add `FAX` in the type for phoneNumber. Looking at the example in the docs https://github.com/nfourtythree/craft-vcard#phonenumber

e.g.
```twig
phoneNumber: {
		number: "+1 234 567 89",
		type: "PREF;WORK;FAX"
	}

```

Let me know how you get on with this

**Comment by waswebb** [comment]
Hi @nfourtythree

Thanks for the Feedback.

The Problem is in the that the `type: "FAX"` don't make his job. In the `Contact App` from Apple the faxnumber will be displayed as phonenumber. 

In the Contact-App it looks like this (the 2th number is a faxnumber): 
<img width="199" alt="bildschirmfoto 2017-04-04 um 09 37 28" src="https://cloud.githubusercontent.com/assets/21307389/24645983/7c8942fa-191a-11e7-95a1-0c9d87a2122c.png">

The same problem with the `type: "VOICE"` for a mobilenumber (the 3th number is a mobilenumber):
<img width="175" alt="bildschirmfoto 2017-04-04 um 09 45 24" src="https://cloud.githubusercontent.com/assets/21307389/24646464/56efcce2-191c-11e7-9a9b-ad1e0a6282ba.png">


Do you have a idea how to fix that?

Thank you for your feedback.

**Comment by nfourtythree** [comment]
@waswebb I think with fax you have to provide `WORK`, `HOME` or `OTHER` with `FAX` for it to work.

So in your example if you change `type: "FAX"` to `type: "WORK;FAX"` does this come up correctly?

**Comment by waswebb** [comment]
`type: "WORK;FAX"` don't  works for me. I get the same output:

<img width="202" alt="bildschirmfoto 2017-04-04 um 10 04 02" src="https://cloud.githubusercontent.com/assets/21307389/24646997/5385dd42-191e-11e7-84fd-a04b7b36daa5.png">

Dose `type: "WORK;FAX"` work in your projects?

**Comment by waswebb** [comment]
I've opened the vCard in a code editor and the code looks like this:

```
TEL;WORK;PREF:+41 61 000 00 00
TEL;WORK;FAX:+41 61 000 00 10
TEL;WORK;VOICE:+41 79 000 00 00
```

Then I have edit the types of number in the `Contact-App` and opened the vCard again in the code editor then I get that code:

```
TEL;type=pref:+41 61 000 00 00
TEL;type=WORK;type=FAX:+41 61 000 00 10
TEL;type=CELL;type=VOICE:+41 79 000 00 00
```

**Comment by nfourtythree** [comment]
@waswebb the last output (the one from the contact app) is the [vCard version 3 specification](https://en.wikipedia.org/wiki/VCard#vCard_3.0). Currently this plugin only outputs vCards in version 2.1 specification. This could be where the issue lays.

The last thing to try might be to swap the order of the keywords and try `type: "FAX;WORK"`. Unfortunately I don't currently have this all setup for testing, and vCard v3 is on the road map but I haven't got round to it yet

**Comment by waswebb** [comment]
@nfourtythree Thank you for your Feedback. I think this is the issue.

I would be happy about a update when you do that. But it's a cool Plugin, thank you for that.

**Comment by nfourtythree** [comment]
@waswebb could you try one last thing and try the following `type: "TYPE=FAX,WORK"` and see if that makes a difference

**Comment by waswebb** [comment]
@nfourtythree Thank you, that works for me 👍
