### ISSUE TITLE
Version for Craft 3?

### ISSUE THREAD

**Issue by kemmerly** [nfourtythree/craft-vcard#8]
Will this plugin be updated for Craft 3? Thanks.

**Comment by nfourtythree** [comment]
Hey @kemmerly 

Thanks for reminding me about this one. Good news is I have started it. Keep an eye out over the next few days!

Thanks 😄

**Comment by nfourtythree** [comment]
@kemmerly This is now available for Craft 3 https://plugins.craftcms.com/vcard
